---
- name: Install nginx
  hosts: webservers
  become: true
  
  tasks:
    - name: ensure apache2 is stopped
      service: 
        name: apache2
        state: stopped
    - name: ensure apache2 uninstalled
      apt: name=apache2 state=absent
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: "start nginx"
      service: 
        name: nginx
        state: started
