  - name: Insta nginx
    block:
      - name: installNginx
        apt:
          name={{item}}
          state=latest
        with_items: 
          - nginx
          - nginx-extras
        tags: InstallNginx
        notify: restart-nginx

      - name: healthChecker
        uri:
          url:  "http://{{ ansible_ssh_host }}"
          return_content: yes
        register: result
        until: '"Welcome to nginx!" in result.content'
        retries: 10
        delay: 1
    when: ansible_facts['distribution'] == 'Ubuntu'
    become: true
    become_user: root
    ignore_errors: true
