---
- name: Call Python script from Ansible playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Python script
      command: python3 inv.py web
      args:
       chdir: library
      register: script_output

    - name: Display script output
      debug:
        var: script_output #.stdout_lines

