---
- hosts: localhost
  

  vars:
    my_color: blue

  tasks:
    - name: "verfiy {{my_color}} is a form of blue"
      assert:
        that: >
          my_color == 'blue' 
          or my_color == 'red'
