---
- name: JsonSearch
  hosts: localhost

  tasks:
    - name: Download
      uri:
        url: https://jsonplaceholder.typicode.com/users
        return_content: yes
      register:  jsoncontent

    - name: JsonSearch
      ansible.builtin.debug:
        msg: "{{ jsoncontent.json | json_query(jmsquery) }}"
      vars:
    #     jmsquery: "[*].{Name: name, Email: email, Phone: phone, CompanyName: company.name, WebSite: website, City: address.city}"
         jmsquery: "[*].{Name: name}"
     #    jmsquery: "[? username==`Samantha`].email"

