---
- name: ReadJsonfile
  hosts: localhost
  tasks:
    - name: Get sales list from Auto Dept
      ansible.builtin.uri:
        url: "http://localhost:8040/sales.json"
        follow_redirects: none
        method: GET
      register: json_output

    - name: JsonSearch
      ansible.builtin.debug:
        msg: "{{ json_output.json | json_query(jmsquery) }}"
      vars:
         jmsquery: "[? trim ==`sedan`]"
      register: auto_sedans