---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distros:
          - centos8
          - debian10

    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install --upgrade pip

      - name: Install test dependencies.
        run: pip3 install -r requirements.txt

      - name: Run molecule tests.
        run: |
          cd apache2
          molecule test 